apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx-namespace
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ =404;
        }
    }
  index.html: |
    <html>
    <body>
    <h1>Hello from NGINX in Kubernetes!</h1>
    </body>
    </html>
