apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  namespace: nginx-namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"