Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    base_config = {
      network: "private_network",
      ip: "192.168.33.1",
      hostname: "webserver",
      provision: {
        type: "shell",
        inline: <<-SHELL
          apt-get update
          apt-get install -y openssh-server
          echo 'vagrant:vagrant' | chpasswd
          sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
          systemctl restart ssh
        SHELL
      }
    }
  
    # Створення трьох віртуальних машин
    (1..3).each do |i|
      config.vm.define "webserver#{i}" do |webserver|
        webserver.vm.network base_config[:network], ip: "192.168.33.1#{i}"
        webserver.vm.hostname = "#{base_config[:hostname]}#{i}"
        webserver.vm.provision base_config[:provision][:type], inline: base_config[:provision][:inline]
      end
    end
  end
  