apiVersion: v1
kind: ConfigMap
metadata:
    name: website-config
data:
    index.html: |
        <html>
        <head><title>Bro EKS</title></head>
        <body><h1>Hello from Bro EKS!!!!!</h1></body>
        </html>
