apiVersion: apps/v1
kind: Deployment
metadata:
    name: static-website
spec:
    replicas: 2
    selector:
        matchLabels:
            app: website
    template:
        metadata:
            labels:
                app: website
        spec:
            containers:
                - name: nginx
                  image: nginx
                  volumeMounts:
                      - name: website-content
                        mountPath: /usr/share/nginx/html
            volumes:
                - name: website-content
                  configMap:
                      name: website-config
