apiVersion: apps/v1
kind: Deployment
metadata:
    name: test-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: test-app
    template:
        metadata:
            labels:
                app: test-app
        spec:
            containers:
                - name: httpd-container
                  image: nginx:latest
                  ports:
                      - containerPort: 80
