Vagrant.configure("2") do |config|
  config.vm.define "privateserver" do |privateserver|
    privateserver.vm.box = "ubuntu/bionic64"
    privateserver.vm.network "private_network", ip: "192.168.33.10"
    privateserver.vm.synced_folder "./data", "/vagrant_data"
    privateserver.vm.provision "shell", path: "provision.sh"
  end
end
